index:
    path: /
    controller: App\Controller\DefaultController::indexAction
homepage:
    path: /homepage
    controller: App\Controller\HomeController::index
app_lucky_number:
    path: /lucky/number/{max}
    controller: App\Controller\LuckyController::number
blog_list:
    path: /blog/{page}
    controller: App\Controller\BlogController::list
    defaults:
        page: 1
    requirements:
        page: \d+
blog_show:
    path: /blog/{slug}
    controller: App\Controller\BlogController::show
article_show:
    path: /articles/{_locale}/{year}/{slug}.{_format}
    controller: App\Controller\ArticleController::show
    defaults:
        _format: html
    requirements:
        _locale: en|fr
        _format: html|rss
        year: \d+